name: BXARM CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  cloud-build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    container:
      image: ghcr.io/fae-emea/bxarm:9.60.2
        
    steps:      
      - name: Checkout project
        uses: actions/checkout@v4

      - name: CMake - Configure
        run: cmake -S. -Bbuild -GNinja
        
      - name: CMake - Build
        run: cmake --build build -j `nproc` --verbose

      - name: C-STAT Analysis
        run: |
             ichecks --all --output build/checks.manifest
             icstat --checks build/checks.manifest --db build/cstat.db analyze -- iccarm tutorial.c

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/sarif/*.sarif
          category: cstat-analysis
